steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '--build-arg'
      - 'HF_TOKEN=${_HF_TOKEN}'
      - '.'
images:
  - '${_IMAGE}'
substitutions:
  _IMAGE: ''
  _HF_TOKEN: ''
