apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/urls: '["https://bible-agent-497880616364.us-central1.run.app","https://bible-agent-2wmxiclx4q-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: bible-agent
  namespace: '497880616364'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: c19ac2f0-c346-4074-97c7-99d2d2cb65f9
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: HF_TOKEN
          value: REPLACE_WITH_HF_TOKEN
        - name: SUPABASE_APP_URL
          value: https://sbuzrogusicxuvgwpqzw.supabase.co
        - name: SUPABASE_APP_KEY
          value: REPLACE_WITH_SUPABASE_APP_KEY
        - name: SUPABASE_VEC_URL
          value: https://qptkclakcrnoochmmrej.supabase.co
        - name: SUPABASE_VEC_KEY
          value: REPLACE_WITH_SUPABASE_VEC_KEY
        image: gcr.io/bible-postoffice-2025/bible-agent:latest
        name: bible-agent-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 497880616364-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
